# Generated by Django 3.2.6 on 2021-09-24 09:11

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('akapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anken',
            name='naiyou',
            field=tinymce.models.HTMLField(),
        ),
    ]
