# Generated by Django 3.2.6 on 2021-09-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akapp', '0003_anken_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anken',
            name='image',
        ),
        migrations.AlterField(
            model_name='anken',
            name='naiyou',
            field=models.TextField(max_length=1000, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='shuho',
            name='naiyou',
            field=models.TextField(max_length=1000, verbose_name='内容'),
        ),
    ]
